BEGIN TRY 
	BEGIN TRANSACTION
	UPDATE Stavka SET CijenaPoKomadu = 38.8404 WHERE IDStavka = 8
	UPDATE Stavka SET CijenaPoKomadu = 18.8404 WHERE IDStavka = 9
	COMMIT TRANSACTION
	PRINT 'Transakcija izvrsena!'
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION
	PRINT 'Transakcija neuspjesna'
	PRINT ERROR_MESSAGE()
END CATCH